# Generated by Django 5.1.4 on 2026-05-19 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Oxirgi aktivlik'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_seconds_active',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami aktiv soniyalar'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessiya',
                'verbose_name_plural': 'Sessiyalar',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='users_users_user_id_4f9013_idx')],
            },
        ),
    ]
