# Generated by Django 5.1.4 on 2026-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_seen_user_total_seconds_active_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demand_access',
            field=models.CharField(choices=[('inherit', 'Global sozlama'), ('on', 'Yoqilgan'), ('off', "O'chirilgan")], default='inherit', max_length=10, verbose_name="Talab ma'lumoti ruxsati"),
        ),
    ]
