# Generated by Django 5.1.4 on 2026-06-03 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_demand_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('info', "Ma'lumot"), ('news', 'Yangilik'), ('reminder', 'Eslatma'), ('promo', 'Aksiya'), ('admin', 'Admin xabari')], default='info', max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('sent_sms', models.BooleanField(default=False)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx')],
            },
        ),
    ]
