# Generated by Django 5.1.4 on 2026-06-03 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Expo push token'),
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('kind', models.CharField(default='admin', max_length=12)),
                ('target', models.CharField(default='all', max_length=20)),
                ('sms', models.BooleanField(default=False)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xabar partiyasi',
                'verbose_name_plural': 'Xabar partiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='users.notificationbatch'),
        ),
    ]
