# Generated by Django 5.1.4 on 2026-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_expo_push_token_notificationbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='preview',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='preview',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
