# Generated by Django 5.1.4 on 2026-05-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom')),
                ('start_address', models.CharField(max_length=255)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_address', models.CharField(max_length=255)),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Sevimli yo'nalish",
                'verbose_name_plural': "Sevimli yo'nalishlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField(blank=True, null=True)),
                ('end_lng', models.FloatField(blank=True, null=True)),
                ('start_address', models.CharField(blank=True, max_length=255)),
                ('end_address', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.FloatField(default=0, verbose_name='Masofa (km)')),
                ('duration_min', models.FloatField(default=0, verbose_name='Vaqt (daqiqa)')),
                ('price_uzs', models.PositiveIntegerField(verbose_name="Narx (so'm)")),
                ('surge', models.FloatField(default=1.0, verbose_name='Surge')),
                ('source', models.CharField(choices=[('formula', 'Tarif formulasi'), ('api', 'Real API'), ('scraped', 'Scraping')], default='formula', max_length=20, verbose_name='Manba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Narx hisob-kitobi',
                'verbose_name_plural': 'Narx hisob-kitoblari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('city', models.CharField(default='Tashkent', max_length=100, verbose_name='Shahar')),
                ('center_lat', models.FloatField(verbose_name='Markaz kenglik')),
                ('center_lng', models.FloatField(verbose_name='Markaz uzunlik')),
                ('radius_km', models.FloatField(default=3.0, verbose_name='Radius (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Tuman / Rayon',
                'verbose_name_plural': 'Tumanlar / Rayonlar',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxiService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='taxi_logos/', verbose_name='Logo')),
                ('color', models.CharField(default='#FFCC00', max_length=7, verbose_name='Brend rang')),
                ('website', models.URLField(blank=True, verbose_name='Veb sayt')),
                ('deeplink_template', models.CharField(blank=True, help_text='Masalan: yandextaxi://route?start-lat={start_lat}&start-lon={start_lng}', max_length=500, verbose_name='Deep-link shabloni')),
                ('base_fare_uzs', models.PositiveIntegerField(default=6000, verbose_name="Bazaviy narx (so'm)")),
                ('per_km_uzs', models.PositiveIntegerField(default=2200, verbose_name="Har 1 km uchun (so'm)")),
                ('per_minute_uzs', models.PositiveIntegerField(default=400, verbose_name="Har 1 daqiqa uchun (so'm)")),
                ('minimum_fare_uzs', models.PositiveIntegerField(default=10000, verbose_name="Minimum narx (so'm)")),
                ('surge_multiplier', models.FloatField(default=1.0, verbose_name="Surge ko'paytuvchi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taxi xizmati',
                'verbose_name_plural': 'Taxi xizmatlari',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
