# Generated by Django 5.1.4 on 2026-05-14 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priceestimate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'city')},
        ),
        migrations.AddField(
            model_name='priceestimate',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxi.region'),
        ),
        migrations.AddField(
            model_name='priceestimate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='taxi.taxiservice'),
        ),
        migrations.AddIndex(
            model_name='priceestimate',
            index=models.Index(fields=['-created_at'], name='taxi_pricee_created_6474b7_idx'),
        ),
        migrations.AddIndex(
            model_name='priceestimate',
            index=models.Index(fields=['service', '-created_at'], name='taxi_pricee_service_9a0799_idx'),
        ),
        migrations.AddIndex(
            model_name='priceestimate',
            index=models.Index(fields=['region', '-created_at'], name='taxi_pricee_region__a64bd3_idx'),
        ),
    ]
