# Generated by Django 5.1.4 on 2026-05-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='geometry',
            field=models.JSONField(blank=True, help_text='OSM dan olingan haqiqiy chegaralar', null=True, verbose_name='GeoJSON polygon'),
        ),
        migrations.AddField(
            model_name='taxiservice',
            name='brand',
            field=models.CharField(blank=True, db_index=True, help_text='Yandex Go, Yango, MyTaxi, Uzum Taxi, ON Taxi', max_length=50, verbose_name='Brend'),
        ),
        migrations.AddField(
            model_name='taxiservice',
            name='tier',
            field=models.CharField(blank=True, choices=[('econom', 'Ekonom/Start'), ('comfort', 'Comfort'), ('comfort_plus', 'Comfort+'), ('business', 'Business'), ('delivery', 'Dostavka')], default='econom', max_length=20, verbose_name='Tarif darajasi'),
        ),
    ]
