# Generated by Django 5.1.4 on 2026-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_region_geometry_taxiservice_brand_taxiservice_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPanelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_enabled', models.BooleanField(default=True, verbose_name="Talab ma'lumoti yoqilgan")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Haydovchi paneli sozlamasi',
                'verbose_name_plural': 'Haydovchi paneli sozlamalari',
            },
        ),
    ]
