# Generated by Django 5.1.4 on 2026-06-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_driverpanelsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiservice',
            name='coverage_area',
            field=models.JSONField(blank=True, help_text='Masalan: {"label": "Toshkent shahri", "min_lat": 41.16, "max_lat": 41.42, "min_lng": 69.10, "max_lng": 69.47}. Bo\'sh bo\'lsa — butun respublika bo\'ylab ishlaydi.', null=True, verbose_name='Xizmat hududi (bbox)'),
        ),
    ]
