# Generated by Django 5.1.4 on 2026-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_priceestimate_searcher_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_color', models.CharField(default='#FFCC00', help_text='Masalan #FFCC00 — butun saytning asosiy rangi.', max_length=7, verbose_name='Brend rangi (HEX)')),
                ('default_theme', models.CharField(choices=[('light', "Yorug'"), ('dark', "Qorong'i"), ('auto', 'Avto')], default='auto', help_text="Foydalanuvchi o'zi tanlamaguncha ko'rinadigan kun/tun rejimi.", max_length=5, verbose_name='Standart rejim')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Sayt ko'rinishi",
                'verbose_name_plural': "Sayt ko'rinishi",
            },
        ),
    ]
