# Generated by Django 5.1.4 on 2026-05-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=100, verbose_name='Karta egasi')),
                ('card_last4', models.CharField(max_length=4, verbose_name='Oxirgi 4 raqam')),
                ('expiry_month', models.PositiveSmallIntegerField(verbose_name='Oy')),
                ('expiry_year', models.PositiveSmallIntegerField(verbose_name='Yil')),
                ('card_type', models.CharField(choices=[('uzcard', 'UzCard'), ('humo', 'Humo'), ('visa', 'Visa')], default='uzcard', max_length=20, verbose_name='Karta turi')),
                ('is_default', models.BooleanField(default=True, verbose_name='Asosiy')),
                ('token', models.CharField(blank=True, help_text="To'lov tizimidan kelgan saqlangan token", max_length=255, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Karta',
                'verbose_name_plural': 'Kartalar',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Sinov muddati'), ('active', 'Faol'), ('expired', 'Muddati tugagan'), ('canceled', 'Bekor qilingan')], default='trial', max_length=20, verbose_name='Holat')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan')),
                ('expires_at', models.DateTimeField(verbose_name='Tugaydi')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Avtomatik yangilanish')),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Oylik narx ($)')),
                ('last_charge_at', models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi to'lov")),
                ('next_charge_at', models.DateTimeField(blank=True, null=True, verbose_name="Keyingi to'lov")),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Summa ($)')),
                ('amount_uzs', models.PositiveIntegerField(default=0, verbose_name="Summa (so'm)")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Karta oxiri')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='Xato xabari')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='Tashqi ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
