# Generated by Django 5.1.4 on 2026-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('uzcard', 'UzCard'), ('humo', 'Humo'), ('visa', 'Visa'), ('mastercard', 'MasterCard')], default='uzcard', max_length=20, verbose_name='Karta turi'),
        ),
    ]
