# Generated by Django 5.1.4 on 2026-06-13 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_card_card_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Kod')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('free_days', models.PositiveIntegerField(default=7, help_text="Obunaga qo'shiladigan kunlar", verbose_name='Bepul kunlar')),
                ('audience', models.CharField(choices=[('all', 'Hammaga'), ('passenger', "Yo'lovchilarga"), ('driver', 'Haydovchilarga')], default='all', max_length=12, verbose_name='Kimga')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='Maksimal foydalanish (0 = cheksiz)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo-kod',
                'verbose_name_plural': 'Promo-kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', "Qo'llandi"), ('expired', 'Muddati tugagan'), ('invalid', 'Yaroqsiz')], default='applied', max_length=12)),
                ('free_days_granted', models.PositiveIntegerField(default=0)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo-kod ishlatilishi',
                'verbose_name_plural': 'Promo-kod ishlatilishlari',
                'ordering': ['-redeemed_at'],
                'unique_together': {('user', 'promo')},
            },
        ),
    ]
