# Generated by Django 5.1.4 on 2026-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_promocode_promoredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text="Keyingi obuna to'loviga chegirma (discount turi uchun)", verbose_name='Chegirma (%)'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='reward_type',
            field=models.CharField(choices=[('free_days', 'Bepul kunlar'), ('discount', 'Obunaga chegirma (%)')], default='free_days', max_length=12, verbose_name='Mukofot turi'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name="Keyingi to'lov chegirmasi (%)"),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='free_days',
            field=models.PositiveIntegerField(default=7, help_text="Obunaga qo'shiladigan kunlar (free_days turi uchun)", verbose_name='Bepul kunlar'),
        ),
    ]
