# Generated by Django 5.1.4 on 2026-07-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_promocode_discount_percent_promocode_reward_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cancel_reason',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Bekor qilish sababi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payme_cancel_time',
            field=models.BigIntegerField(default=0, verbose_name='Payme bekor qilingan (ms)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payme_create_time',
            field=models.BigIntegerField(default=0, verbose_name='Payme yaratilgan (ms)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payme_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Payme tranzaksiya ID'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payme_perform_time',
            field=models.BigIntegerField(default=0, verbose_name="Payme to'langan (ms)"),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payme_state',
            field=models.SmallIntegerField(choices=[(0, 'Yaratilmagan'), (1, 'Yaratilgan'), (2, "To'langan"), (-1, 'Bekor qilingan'), (-2, "To'langach qaytarilgan")], default=0, verbose_name='Payme holati'),
        ),
    ]
