# Generated by Django 5.1.4 on 2026-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_transaction_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoredemption',
            name='discount_percent_granted',
            field=models.PositiveIntegerField(default=0, verbose_name='Berilgan chegirma (%)'),
        ),
        migrations.AlterField(
            model_name='promoredemption',
            name='free_days_granted',
            field=models.PositiveIntegerField(default=0, verbose_name='Berilgan bepul kunlar'),
        ),
    ]
