# Generated by Django 5.1.4 on 2026-05-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyServiceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('avg_price_uzs', models.PositiveIntegerField(default=0, verbose_name="O'rtacha narx (so'm)")),
                ('min_price_uzs', models.PositiveIntegerField(default=0, verbose_name='Eng past narx')),
                ('max_price_uzs', models.PositiveIntegerField(default=0, verbose_name='Eng yuqori narx')),
                ('avg_distance_km', models.FloatField(default=0, verbose_name="O'rtacha masofa (km)")),
                ('avg_duration_min', models.FloatField(default=0, verbose_name="O'rtacha vaqt (daqiqa)")),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name="So'rovlar soni")),
                ('cheapest_count', models.PositiveIntegerField(default=0, verbose_name="Eng arzon bo'lgan marotaba")),
            ],
            options={
                'verbose_name': 'Kunlik statistika',
                'verbose_name_plural': 'Kunlik statistikalar',
                'ordering': ['-date', 'service'],
            },
        ),
    ]
