# Generated by Django 5.1.4 on 2026-05-14 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyservicestat',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_stats', to='taxi.region'),
        ),
        migrations.AddField(
            model_name='dailyservicestat',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='taxi.taxiservice'),
        ),
        migrations.AddIndex(
            model_name='dailyservicestat',
            index=models.Index(fields=['-date', 'service'], name='stats_daily_date_c368f6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyservicestat',
            index=models.Index(fields=['-date', 'region'], name='stats_daily_date_e7b0ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyservicestat',
            unique_together={('date', 'service', 'region')},
        ),
    ]
