# Generated by Django 5.1.4 on 2026-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='econom', max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(default='#5C6772', max_length=7)),
                ('day', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('price_uzs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Soatlik narx surati',
                'verbose_name_plural': 'Soatlik narx suratlari',
                'indexes': [models.Index(fields=['day', 'tier'], name='stats_hourl_day_3ca7e7_idx')],
                'unique_together': {('tier', 'brand', 'day', 'hour')},
            },
        ),
    ]
